#!/bin/bash

CURRENTPATH="$(pwd -P)"

LCS_BASE=$CURRENTPATH/base
LCS_DEVICES=$CURRENTPATH/devices
LCS_SERVICES=$CURRENTPATH/services

export LCS_SERVICES=$LCS_SERVICES
export LCS_LOGFILES=$CURRENTPATH/log/
export PYTHONPATH=$PYTHONPATH:$LCS_BASE:$LCS_DEVICES:$LCS_SERVICES


