//
// File generated by /opt/root5.26/bin/rootcint at Tue Aug 28 15:22:51 2012

// Do NOT change. Changes will be lost next time file is generated
//

#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "GUItestCint.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void MyMainFrame_ShowMembers(void *obj, TMemberInspector &R__insp, char *R__parent);
   static void delete_MyMainFrame(void *p);
   static void deleteArray_MyMainFrame(void *p);
   static void destruct_MyMainFrame(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::MyMainFrame*)
   {
      ::MyMainFrame *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::MyMainFrame >(0);
      static ::ROOT::TGenericClassInfo 
         instance("MyMainFrame", ::MyMainFrame::Class_Version(), "./GUItest.h", 17,
                  typeid(::MyMainFrame), DefineBehavior(ptr, ptr),
                  &::MyMainFrame::Dictionary, isa_proxy, 4,
                  sizeof(::MyMainFrame) );
      instance.SetDelete(&delete_MyMainFrame);
      instance.SetDeleteArray(&deleteArray_MyMainFrame);
      instance.SetDestructor(&destruct_MyMainFrame);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::MyMainFrame*)
   {
      return GenerateInitInstanceLocal((::MyMainFrame*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::MyMainFrame*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

//______________________________________________________________________________
TClass *MyMainFrame::fgIsA = 0;  // static to hold class pointer

//______________________________________________________________________________
const char *MyMainFrame::Class_Name()
{
   return "MyMainFrame";
}

//______________________________________________________________________________
const char *MyMainFrame::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::MyMainFrame*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int MyMainFrame::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::MyMainFrame*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void MyMainFrame::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::MyMainFrame*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *MyMainFrame::Class()
{
   if (!fgIsA) fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::MyMainFrame*)0x0)->GetClass();
   return fgIsA;
}

//______________________________________________________________________________
void MyMainFrame::Streamer(TBuffer &R__b)
{
   // Stream an object of class MyMainFrame.

   if (R__b.IsReading()) {
      R__b.ReadClassBuffer(MyMainFrame::Class(),this);
   } else {
      R__b.WriteClassBuffer(MyMainFrame::Class(),this);
   }
}

//______________________________________________________________________________
void MyMainFrame::ShowMembers(TMemberInspector &R__insp, char *R__parent)
{
      // Inspect the data members of an object of class MyMainFrame.
      TClass *R__cl = ::MyMainFrame::IsA();
      Int_t R__ncp = strlen(R__parent);
      if (R__ncp || R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__parent, "*fEcanvas0", &fEcanvas0);
      R__insp.Inspect(R__cl, R__parent, "*fEcanvas1", &fEcanvas1);
      R__insp.Inspect(R__cl, R__parent, "*fEcanvas2", &fEcanvas2);
      R__insp.Inspect(R__cl, R__parent, "*fEcanvas3", &fEcanvas3);
      R__insp.Inspect(R__cl, R__parent, "*fEcanvas4", &fEcanvas4);
      R__insp.Inspect(R__cl, R__parent, "*fEcanvas5", &fEcanvas5);
      R__insp.Inspect(R__cl, R__parent, "*fEcanvas6", &fEcanvas6);
      R__insp.Inspect(R__cl, R__parent, "*fEcanvas7", &fEcanvas7);
      TGMainFrame::ShowMembers(R__insp, R__parent);
}

namespace ROOT {
   // Wrapper around operator delete
   static void delete_MyMainFrame(void *p) {
      delete ((::MyMainFrame*)p);
   }
   static void deleteArray_MyMainFrame(void *p) {
      delete [] ((::MyMainFrame*)p);
   }
   static void destruct_MyMainFrame(void *p) {
      typedef ::MyMainFrame current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::MyMainFrame

/********************************************************
* GUItestCint.cc
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableGUItestCint();

extern "C" void G__set_cpp_environmentGUItestCint() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("GUItest.h");
  G__cpp_reset_tagtableGUItestCint();
}
#include <new>
extern "C" int G__cpp_dllrevGUItestCint() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* MyMainFrame */
static int G__GUItestCint_318_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   MyMainFrame* p = NULL;
   char* gvp = (char*) G__getgvp();
   //m: 4
   if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
     p = new MyMainFrame(
(const TGWindow*) G__int(libp->para[0]), (UInt_t) G__int(libp->para[1])
, (UInt_t) G__int(libp->para[2]), (Int_t) G__int(libp->para[3]));
   } else {
     p = new((void*) gvp) MyMainFrame(
(const TGWindow*) G__int(libp->para[0]), (UInt_t) G__int(libp->para[1])
, (UInt_t) G__int(libp->para[2]), (Int_t) G__int(libp->para[3]));
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__GUItestCintLN_MyMainFrame));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GUItestCint_318_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((MyMainFrame*) G__getstructoffset())->Ch_Histo((int) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GUItestCint_318_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((MyMainFrame*) G__getstructoffset())->quit();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GUItestCint_318_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) MyMainFrame::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GUItestCint_318_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) MyMainFrame::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GUItestCint_318_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) MyMainFrame::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GUItestCint_318_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      MyMainFrame::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GUItestCint_318_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((MyMainFrame*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GUItestCint_318_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) MyMainFrame::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GUItestCint_318_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) MyMainFrame::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GUItestCint_318_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) MyMainFrame::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GUItestCint_318_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) MyMainFrame::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef MyMainFrame G__TMyMainFrame;
static int G__GUItestCint_318_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (MyMainFrame*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((MyMainFrame*) (soff+(sizeof(MyMainFrame)*i)))->~G__TMyMainFrame();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (MyMainFrame*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((MyMainFrame*) (soff))->~G__TMyMainFrame();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* MyMainFrame */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncGUItestCint {
 public:
  G__Sizep2memfuncGUItestCint(): p(&G__Sizep2memfuncGUItestCint::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncGUItestCint::*p)();
};

size_t G__get_sizep2memfuncGUItestCint()
{
  G__Sizep2memfuncGUItestCint a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceGUItestCint() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__GUItestCintLN_MyMainFrame))) {
     MyMainFrame *G__Lderived;
     G__Lderived=(MyMainFrame*)0x1000;
     {
       TGMainFrame *G__Lpbase=(TGMainFrame*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__GUItestCintLN_MyMainFrame),G__get_linked_tagnum(&G__GUItestCintLN_TGMainFrame),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
     {
       TGCompositeFrame *G__Lpbase=(TGCompositeFrame*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__GUItestCintLN_MyMainFrame),G__get_linked_tagnum(&G__GUItestCintLN_TGCompositeFrame),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TGFrame *G__Lpbase=(TGFrame*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__GUItestCintLN_MyMainFrame),G__get_linked_tagnum(&G__GUItestCintLN_TGFrame),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TGWindow *G__Lpbase=(TGWindow*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__GUItestCintLN_MyMainFrame),G__get_linked_tagnum(&G__GUItestCintLN_TGWindow),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TGObject *G__Lpbase=(TGObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__GUItestCintLN_MyMainFrame),G__get_linked_tagnum(&G__GUItestCintLN_TGObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__GUItestCintLN_MyMainFrame),G__get_linked_tagnum(&G__GUItestCintLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TQObject *G__Lpbase=(TQObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__GUItestCintLN_MyMainFrame),G__get_linked_tagnum(&G__GUItestCintLN_TQObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableGUItestCint() {

   /* Setting up typedef entry */
   G__search_typename2("Int_t",105,-1,0,-1);
   G__setnewtype(-1,"Signed integer 4 bytes (int)",0);
   G__search_typename2("UInt_t",104,-1,0,-1);
   G__setnewtype(-1,"Unsigned integer 4 bytes (unsigned int)",0);
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<TSchemaHelper>",117,G__get_linked_tagnum(&G__GUItestCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__GUItestCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__GUItestCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__GUItestCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__GUItestCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__GUItestCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__GUItestCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__GUItestCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__GUItestCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__GUItestCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* MyMainFrame */
static void G__setup_memvarMyMainFrame(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__GUItestCintLN_MyMainFrame));
   { MyMainFrame *p; p=(MyMainFrame*)0x1000; if (p) { }
   G__memvar_setup((void*)(&MyMainFrame::n_histo),105,0,0,-1,-1,-2,1,"n_histo=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->fEcanvas0)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__GUItestCintLN_TRootEmbeddedCanvas),-1,-1,1,"fEcanvas0=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->fEcanvas1)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__GUItestCintLN_TRootEmbeddedCanvas),-1,-1,1,"fEcanvas1=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->fEcanvas2)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__GUItestCintLN_TRootEmbeddedCanvas),-1,-1,1,"fEcanvas2=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->fEcanvas3)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__GUItestCintLN_TRootEmbeddedCanvas),-1,-1,1,"fEcanvas3=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->fEcanvas4)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__GUItestCintLN_TRootEmbeddedCanvas),-1,-1,1,"fEcanvas4=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->fEcanvas5)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__GUItestCintLN_TRootEmbeddedCanvas),-1,-1,1,"fEcanvas5=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->fEcanvas6)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__GUItestCintLN_TRootEmbeddedCanvas),-1,-1,1,"fEcanvas6=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->fEcanvas7)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__GUItestCintLN_TRootEmbeddedCanvas),-1,-1,1,"fEcanvas7=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GUItestCintLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarGUItestCint() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncMyMainFrame(void) {
   /* MyMainFrame */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__GUItestCintLN_MyMainFrame));
   G__memfunc_setup("MyMainFrame",1078,G__GUItestCint_318_0_1, 105, G__get_linked_tagnum(&G__GUItestCintLN_MyMainFrame), -1, 0, 4, 1, 1, 0, 
"U 'TGWindow' - 10 - p h - 'UInt_t' 0 - w "
"h - 'UInt_t' 0 - h i - 'Int_t' 0 - NFILE", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Ch_Histo",785,G__GUItestCint_318_0_2, 121, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - n", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("quit",451,G__GUItestCint_318_0_3, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__GUItestCint_318_0_4, 85, G__get_linked_tagnum(&G__GUItestCintLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&MyMainFrame::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__GUItestCint_318_0_5, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&MyMainFrame::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__GUItestCint_318_0_6, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&MyMainFrame::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__GUItestCint_318_0_7, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&MyMainFrame::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__GUItestCintLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 2, 1, 1, 0, 
"u 'TMemberInspector' - 1 - insp C - - 0 - parent", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__GUItestCint_318_0_11, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__GUItestCint_318_0_12, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&MyMainFrame::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__GUItestCint_318_0_13, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&MyMainFrame::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__GUItestCint_318_0_14, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&MyMainFrame::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__GUItestCint_318_0_15, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&MyMainFrame::DeclFileLine) ), 0);
   // automatic destructor
   G__memfunc_setup("~MyMainFrame", 1204, G__GUItestCint_318_0_16, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncGUItestCint() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {
}

static void G__cpp_setup_global3() {
}

static void G__cpp_setup_global4() {
}

static void G__cpp_setup_global5() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalGUItestCint() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
  G__cpp_setup_global3();
  G__cpp_setup_global4();
  G__cpp_setup_global5();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcGUItestCint() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__GUItestCintLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__GUItestCintLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__GUItestCintLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__GUItestCintLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__GUItestCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__GUItestCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__GUItestCintLN_TGObject = { "TGObject" , 99 , -1 };
G__linked_taginfo G__GUItestCintLN_TQObject = { "TQObject" , 99 , -1 };
G__linked_taginfo G__GUItestCintLN_TGWindow = { "TGWindow" , 99 , -1 };
G__linked_taginfo G__GUItestCintLN_TGFrame = { "TGFrame" , 99 , -1 };
G__linked_taginfo G__GUItestCintLN_TGCompositeFrame = { "TGCompositeFrame" , 99 , -1 };
G__linked_taginfo G__GUItestCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__GUItestCintLN_TGMainFrame = { "TGMainFrame" , 99 , -1 };
G__linked_taginfo G__GUItestCintLN_TRootEmbeddedCanvas = { "TRootEmbeddedCanvas" , 99 , -1 };
G__linked_taginfo G__GUItestCintLN_MyMainFrame = { "MyMainFrame" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableGUItestCint() {
  G__GUItestCintLN_TClass.tagnum = -1 ;
  G__GUItestCintLN_TBuffer.tagnum = -1 ;
  G__GUItestCintLN_TMemberInspector.tagnum = -1 ;
  G__GUItestCintLN_TObject.tagnum = -1 ;
  G__GUItestCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__GUItestCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__GUItestCintLN_TGObject.tagnum = -1 ;
  G__GUItestCintLN_TQObject.tagnum = -1 ;
  G__GUItestCintLN_TGWindow.tagnum = -1 ;
  G__GUItestCintLN_TGFrame.tagnum = -1 ;
  G__GUItestCintLN_TGCompositeFrame.tagnum = -1 ;
  G__GUItestCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__GUItestCintLN_TGMainFrame.tagnum = -1 ;
  G__GUItestCintLN_TRootEmbeddedCanvas.tagnum = -1 ;
  G__GUItestCintLN_MyMainFrame.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableGUItestCint() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__GUItestCintLN_TClass);
   G__get_linked_tagnum_fwd(&G__GUItestCintLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__GUItestCintLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__GUItestCintLN_TObject);
   G__get_linked_tagnum_fwd(&G__GUItestCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__GUItestCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__GUItestCintLN_TGObject);
   G__get_linked_tagnum_fwd(&G__GUItestCintLN_TQObject);
   G__get_linked_tagnum_fwd(&G__GUItestCintLN_TGWindow);
   G__get_linked_tagnum_fwd(&G__GUItestCintLN_TGFrame);
   G__get_linked_tagnum_fwd(&G__GUItestCintLN_TGCompositeFrame);
   G__get_linked_tagnum_fwd(&G__GUItestCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__get_linked_tagnum_fwd(&G__GUItestCintLN_TGMainFrame);
   G__get_linked_tagnum_fwd(&G__GUItestCintLN_TRootEmbeddedCanvas);
   G__tagtable_setup(G__get_linked_tagnum(&G__GUItestCintLN_MyMainFrame),sizeof(MyMainFrame),-1,324608,(char*)NULL,G__setup_memvarMyMainFrame,G__setup_memfuncMyMainFrame);
}
extern "C" void G__cpp_setupGUItestCint(void) {
  G__check_setup_version(30051515,"G__cpp_setupGUItestCint()");
  G__set_cpp_environmentGUItestCint();
  G__cpp_setup_tagtableGUItestCint();

  G__cpp_setup_inheritanceGUItestCint();

  G__cpp_setup_typetableGUItestCint();

  G__cpp_setup_memvarGUItestCint();

  G__cpp_setup_memfuncGUItestCint();
  G__cpp_setup_globalGUItestCint();
  G__cpp_setup_funcGUItestCint();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncGUItestCint();
  return;
}
class G__cpp_setup_initGUItestCint {
  public:
    G__cpp_setup_initGUItestCint() { G__add_setup_func("GUItestCint",(G__incsetup)(&G__cpp_setupGUItestCint)); G__call_setup_funcs(); }
   ~G__cpp_setup_initGUItestCint() { G__remove_setup_func("GUItestCint"); }
};
G__cpp_setup_initGUItestCint G__cpp_setup_initializerGUItestCint;

