######################################################################
# Automatically generated by qmake (1.07a) Wed Feb 11 15:23:57 2009
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += GUI_schema.h
SOURCES += GUI_schema.cpp main.C
